--- 
- hosts: localhost
  tasks:
    - name: send a message to chat in playbook
      community.general.telegram:
        token: "{{ Telegram_Token }}"
        api_args:
          chat_id: "{{ Telegram_ChatID }}"
          parse_mode: "html"
          text: "Start to deploy project {{project_name }} on branch {{ git_branch }} with url {{ git_repo }} by {{ build_user }}."
          disable_web_page_preview: True
    - name: Clone repository
      git:
        repo: "{{ git_repo }}"
        version: "{{ git_branch }}"
        dest: "{{ workspace }}/{{ project_name }}"
        accept_hostkey: yes
        update: yes
        force: yes
      ignore_errors: True
      register: cloned