--- 
- hosts: localhost 
  tasks: 
    - name: send notify to team via telegram 
      community.general.telegram:
        token: "8345257146:AAHnSLoXB8VG9fMG8DmfZx34cb7I4FquUiw"
        api_args:
          chat_id: "-5281328330"
          parse_mode: "html"
          text: "Start to deploy project employee-api on branch master with url https://github.com/sothylorn/employee-api.git by sothy."
          disable_web_page_preview: True
    - name: clone project source code 
      git:
        repo: "https://github.com/sothylorn/employee-api.git"
        version: "master"
        dest: "/var/lib/jenkins/ansible-pipline/employee-api"
        accept_hostkey: yes
        update: yes
        force: yes
      ignore_errors: True